#!/bin/zsh

# MAKE .TMP
dir=$AZULE/Work
mkdir -p "$dir"/DEBS
mkdir -p "$dir"/JSONS

# DECLARE $TWEAKNAME
echo "Project Name:"
read tweakname
if [ -z "$tweakname" ]
then
tweakname="package"
fi

# MAKE .TMP/$TWEAKNAME
mkdir -p "$dir"/"$tweakname"
cd "$dir"/"$tweakname"

# GET IPA
echo "IPA Directory:"
read ipadir

# PREPARE IPA
unzip -q "$ipadir" -d "$dir"/"$tweakname"

# SET OUTPUT DIRECTORY
# echo "Output Directory:"
# read outdir

# GET DEBS
echo "Tweaks(BundleID's or DEB Directories) (required):"
twk=()
vared twk
tweakids=( $twk )
for i in "${tweakids[@]}"
do
if [ -f "$i" ]
then
rsync -a "$i" "$dir"/DEBS
dpkg -x "$dir"/DEBS/$(basename "$i") .

else

# FETCH TWEAK JSONS AND DEBS

# GET TWEAK JSONS
curl -s -o "$dir"/JSONS/"$i".json https://api.parcility.co/db/package/"$i"

# GET TWEAK DEBS FROM PARCILITY
curl -s -o "$dir/DEBS/$i.deb" "$(jq -r '.data.repo.url' "$dir"/JSONS/"$i".json)$(jq -r '.data.builds[].Filename' "$dir"/JSONS/"$i".json)"
dpkg -x "$dir"/DEBS/"$i".deb .
fi
done

echo "DYLIBs to Inject (required):"
dlb=()
vared dlb
dylibnames=( $dlb )

# PREPARE BUNDLES
find -E "$dir"/"$tweakname"/Library/Application\ Support -iname '*.bundle' ! -iregex '.*\.(bundle)/.+' -exec rsync -a {} Payload/*.app \;

# PREPARE SUBSTRATE
rsync -a $AZULE/CydiaSubstrate.framework Payload/*.app/Frameworks

# PREPARE AND INJECT DYLIBS
executable=("$dir"/"$tweakname"/Payload/*.app/$(/usr/libexec/PlistBuddy -c "Print :CFBundleExecutable" Payload/*.app/Info.plist))
for i in "${dylibnames[@]}"
do
codesign --remove-signature 'Library/MobileSubstrate/DynamicLibraries/'$i''
rsync -a 'Library/MobileSubstrate/DynamicLibraries/'$i'' Payload/*.app/Frameworks
install_name_tool -change /Library/Frameworks/CydiaSubstrate.framework/CydiaSubstrate @rpath/CydiaSubstrate.framework/CydiaSubstrate Payload/*.app/Frameworks/"$i"
$AZULE/insert_dylib --inplace --all-yes "@rpath/$i" "$executable"
done

# PATCH INFO.PLIST
plutil -remove UISupportedDevices "$dir"/"$tweakname"/Payload/*.app/Info.plist

# GENERATE IPA
mkdir -p $AZULE/Packages
zip -r -q -X $AZULE/Packages/$tweakname.ipa Payload

# CLEANUP
rm -rf "$dir"
