#!/bin/zsh

while true; do
    printf "Are you sure you want to delete Azule? [y/n]: "
    read yn
    case $yn in
        [Yy]* )
            unlink /usr/local/bin/update-azule
            unlink /usr/local/bin/azule
            rm -rf $AZULE
            break
            ;;
        [Nn]* ) exit;;
    esac
done
